version: '2'
services:
  wordpress:
    image: wordpress
    links:
      - wordpress_db:mysql
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: pass
    working_dir: /var/www/html
    volumes:
      - ./wordpress/:/var/www/html

  wordpress_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8082:80"
    links:
      - wordpress_db:mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: pass
      PMA_HOST: wordpress_db

